# Inspired by https://github.com/nginx-proxy/acme-companion/blob/main/docs/Docker-Compose.md
services:
  nginx-proxy:
    image: nginx:alpine
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - conf:/etc/nginx/conf.d
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - certs:/etc/nginx/certs:ro
    restart: always
    networks:
      - nginx-proxy_default

  nginx-gen:
    image: nginxproxy/docker-gen:0.14.2
    container_name: nginx-gen
    volumes:
      - vhost:/etc/nginx/vhost.d
      - conf:/etc/nginx/conf.d
      - html:/usr/share/nginx/html
      - certs:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro
    command: -notify-sighup nginx-proxy -watch /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
    restart: always
    networks:
      - nginx-proxy_default

  acme-companion:
    image: nginxproxy/acme-companion:2.5.0
    container_name: nginx-proxy-acme
    environment:
      NGINX_DOCKER_GEN_CONTAINER: nginx-gen
      NGINX_PROXY_CONTAINER: nginx-proxy
      # Change this to receive warnings about expiring certificates and for account recovery
      DEFAULT_EMAIL: webmaster@aam-digital.com
    volumes:
      - conf:/etc/nginx/conf.d
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - certs:/etc/nginx/certs:rw
      - acme:/etc/acme.sh
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: always
    networks:
      - nginx-proxy_default

volumes:
  conf:
  vhost:
  html:
  certs:
  acme:

networks:
  nginx-proxy_default:
    external: true
