version: '3'

services:
  app:
    image: aamdigital/ndb-server:dev
    networks:
      - internal
      - nginx-proxy_default
    depends_on:
#      - backend
      - couchdb
    volumes:
      - ./config.json:/usr/share/nginx/html/assets/config.json
      - ./child-photos:/usr/share/nginx/html/assets/child-photos
      - ./keycloak.json:/usr/share/nginx/html/assets/keycloak.json
    environment:
      VIRTUAL_HOST: example.com
      LETSENCRYPT_HOST: example.com
#      COUCHDB_URL: http://backend:3000
      COUCHDB_URL: http://couchdb:5984
    restart: unless-stopped

#  backend:
#    image: aamdigital/replication-ms:latest
#    networks:
#      - internal
#    depends_on:
#      - couchdb
#    environment:
#      DATABASE_URL: http://couchdb:5984
#      DATABASE_NAME: app
#      # Same as COUCHDB_USER and COUCHDB_PASSWORD
#      DATABASE_USER: admin
#      DATABASE_PASSWORD: PASSWORD
#      JWT_SECRET: MY_JWT_SECRET
#      JWT_PUBLIC_KEY: "-----BEGIN PUBLIC KEY-----\n<PUBLIC_KEY>\n-----END PUBLIC KEY-----"
#      SENTRY_DSN:
#    restart: unless-stopped

  couchdb:
    image: couchdb:3
    networks:
      - internal
    volumes:
      - ./couchdb/data:/opt/couchdb/data
      - ./couchdb.ini:/opt/couchdb/etc/local.d/couchdb.ini
    environment:
      COUCHDB_USER: admin
      COUCHDB_PASSWORD: PASSWORD
    restart: unless-stopped

networks:
  internal:
  nginx-proxy_default:
    external: true
