version: '3'

services:
  app:
    image: aamdigitaltravis/ndb-server:${VERSION:?No release specified}
    networks:
      - internal
      - nginx-proxy_default
    depends_on:
      - backend
    volumes:
      - ./config.json:/usr/share/nginx/html/assets/config.json
      - ./child-photos:/usr/share/nginx/html/assets/child-photos
      #- ./keycloak.json:/usr/share/nginx/html/assets/keycloak.json
    environment:
      VIRTUAL_HOST: ${APP_URL:?App URL not set}
      LETSENCRYPT_HOST: ${APP_URL:?App URL not set}
      COUCHDB_URL: http://backend:3000
    restart: unless-stopped

  backend:
    image: aamdigitaltravis/replication-ms:latest
    networks:
      - internal
    depends_on:
      - couchdb
    environment:
      DATABASE_URL: http://couchdb:5984
      DATABASE_NAME: app
      DATABASE_USER: admin
      DATABASE_PASSWORD: ${COUCHDB_PASSWORD:?Admin password not set}
      JWT_SECRET: ${JWT_SECRET:?JWT secret not set}
      JWT_PUBLIC_KEY: "-----BEGIN PUBLIC KEY-----\n${PUBLIC_KEY}\n-----END PUBLIC KEY-----"
      SENTRY_DSN: ${SENTRY_DSN}
    restart: unless-stopped

  couchdb:
    image: couchdb:3
    networks:
      - internal
    volumes:
      - ./couchdb/data:/opt/couchdb/data
      - ./couchdb.ini:/opt/couchdb/etc/local.d/couchdb.ini
    environment:
      COUCHDB_USER: admin
      COUCHDB_PASSWORD: ${COUCHDB_PASSWORD:?Admin password not set}
    restart: unless-stopped

networks:
  internal:
  nginx-proxy_default:
    external: true
