version: '3'

services:
  app:
    image: aamdigital/ndb-server:dev
    networks:
      - internal
      - nginx-proxy_default
    depends_on:
      - couchdb
    volumes:
      - ./config.json:/usr/share/nginx/html/assets/config.json
      - ./child-photos:/usr/share/nginx/html/assets/child-photos
    environment:
      VIRTUAL_HOST: example.com
      LETSENCRYPT_HOST: example.com
      LETSENCRYPT_EMAIL: webmaster@example.com
      WEBDAV_URL: http://localhost
      COUCHDB_URL: http://backend:3000
    restart: unless-stopped

  backend:
    image: backend:latest
    networks:
      - internal
    depends_on:
      - couchdb
    environment:
      DATABASE_URL: http://couchdb:5984
      DATABASE_USER: admin
      DATABASE_PASSWORD: PASSWORD

  couchdb:
    image: couchdb:3
    networks:
      - internal
    volumes:
      - ./couchdb/data:/opt/couchdb/data
    environment:
      COUCHDB_USER: admin
      COUCHDB_PASSWORD: PASSWORD
    restart: unless-stopped


networks:
  internal:
  nginx-proxy_default:
    external: true
