version: '3'

services:
  app:
    image: aamdigital/ndb-server:${VERSION:?No release specified}
    networks:
      - internal
      - nginx-proxy_default
    depends_on:
      - ${COMPOSE_PROFILES:-couchdb}
    volumes:
      - ./config.json:/usr/share/nginx/html/assets/config.json
      - ./keycloak.json:/usr/share/nginx/html/assets/keycloak.json
    environment:
      VIRTUAL_HOST: ${APP_URL:?App URL not set}
      LETSENCRYPT_HOST: ${APP_URL:?App URL not set}
      COUCHDB_URL: http://${COMPOSE_PROFILES:-couchdb}:5984
      QUERY_URL: http://query:3000
    restart: unless-stopped

  # (optional) backend. Only deployed if "COMPOSE_PROFILES=backend" is set in the `.env` file
  backend:
    image: aamdigital/replication-ms:latest
    networks:
      - internal
    depends_on:
      - couchdb
    environment:
      DATABASE_URL: http://couchdb:5984
      DATABASE_NAME: app
      DATABASE_USER: admin
      DATABASE_PASSWORD: ${COUCHDB_PASSWORD:?Admin password not set}
      JWT_SECRET: ${JWT_SECRET:?JWT secret not set}
      JWT_PUBLIC_KEY: "-----BEGIN PUBLIC KEY-----\n${PUBLIC_KEY}\n-----END PUBLIC KEY-----"
      SENTRY_DSN: ${SENTRY_DSN}
      PORT: 5984
    restart: unless-stopped
    profiles:
      - backend

  couchdb:
    image: couchdb:3
    networks:
      - internal
    volumes:
      - ./couchdb/data:/opt/couchdb/data
      - ./couchdb.ini:/opt/couchdb/etc/local.d/couchdb.ini
    environment:
      COUCHDB_USER: admin
      COUCHDB_PASSWORD: ${COUCHDB_PASSWORD:?Admin password not set}
    restart: unless-stopped

  query:
    image: aamdigital/query-ms:latest
    networks:
      - internal
    environment:
      SENTRY_DSN: ${SENTRY_DSN}
      DATABASE_URL: http://${COMPOSE_PROFILES:-couchdb}:5984
      DATABASE_PASSWORD: ${COUCHDB_PASSWORD}
      QUERY_URL: "http://sqs:4984"
    profiles:
      - ${SQS_PROFILE:-other}

  sqs:
    build: ${SETUP_DIR:-/var/docker/setup}
    networks:
      - internal
    depends_on:
      - couchdb
    volumes:
      - ./sqs:/data
    environment:
      COUCHDB_URL: http://couchdb:5984
    profiles:
      # We currently use the `COMPOSE_PROFILES` value to create URLs, so we cannot set multiple profiles there.
      # Therefore this uses a variable to set the name of the profile instead.
      - ${SQS_PROFILE:-other}

networks:
  internal:
  nginx-proxy_default:
    external: true
