version: '3'

services:
  app:
    image: aamdigital/ndb-server:dev
    networks:
      - internal
      - nginx-proxy_default
    depends_on:
      - couchdb
    volumes:
      - ./config.json:/usr/share/nginx/html/assets/config.json
      - ./child-photos:/usr/share/nginx/html/assets/child-photos
    environment:
      VIRTUAL_HOST: example.com
      LETSENCRYPT_HOST: example.com
      WEBDAV_URL: http://localhost
      COUCHDB_URL: http://couchdb:5984
    restart: unless-stopped

  couchdb:
    image: couchdb:3
    networks:
      - internal
    volumes:
      - ./couchdb/data:/opt/couchdb/data
      - ./couchdb.ini:/opt/couchdb/etc/local.d/couchdb.ini
    environment:
      COUCHDB_USER: admin
      COUCHDB_PASSWORD: PASSWORD
    restart: unless-stopped

networks:
  internal:
  nginx-proxy_default:
    external: true
