version: '3'

services:
  app:
    image: aamdigital/ndb-server:2.7.1
    networks:
      - internal
      - nginx-proxy_default
    depends_on:
      - couchdb
    volumes:
      - ./config.json:/usr/share/nginx/html/assets/config.json
      - ./child-photos:/usr/share/nginx/html/assets/child-photos
    environment:
      VIRTUAL_HOST: example.com
      LETSENCRYPT_HOST: example.com
      LETSENCRYPT_EMAIL: webmaster@example.com
    restart: unless-stopped

  couchdb:
    image: couchdb
    networks:
      - internal
    volumes:
      - ./couchdb/data:/opt/couchdb/data
    environment:
      COUCHDB_USER: admin
      COUCHDB_PASSWORD: PASSWORD
    ports:
      - 5986:5986
    restart: unless-stopped


networks:
  internal:
  nginx-proxy_default:
    external: true
