version: '3'

services:
  webserver:
    image: aamdigital/ndb-server:2.5.3
    container_name: ndb-server
    networks:
      - internal
#     - nginx-proxy_default
    depends_on:
      - couchdb
    volumes:
      - ./assets:/usr/share/nginx/html/assets
    environment:
      VIRTUAL_HOST: example.com
      LETSENCRYPT_HOST: example.com
      LETSENCRYPT_EMAIL: webmaster@example.com
    restart: unless-stopped
    ports:
      - 80:80

  couchdb:
    image: couchdb
    networks:
      - internal
    volumes:
      - ./couchdb/data:/opt/couchdb/data
    environment:
      COUCHDB_USER: admin
      COUCHDB_PASSWORD: PASSWORD
    restart: unless-stopped


networks:
  internal:
#  nginx-proxy_default:
#    external: true

