version: '3'

services:
  keycloak:
    # Building from local Dockerfile
    build: .
    environment:
      # For all available options see https://www.keycloak.org/server/all-config
      KEYCLOAK_ADMIN: admin
      KC_DB_URL_HOST: postgres
      KC_DB_USERNAME: keycloak
      KC_PROXY: edge
      # Adjust the following values
      # TODO introduce variables
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB_PASSWORD: PASSWORD
      KC_HOSTNAME: example.com
      LETSENCRYPT_HOST: example.com
      VIRTUAL_HOST: example.com
      VIRTUAL_PORT: 8080
    volumes:
      - ./aam-theme:/opt/keycloak/themes/aam-theme
    command: start --optimized --spi-theme-login-theme=aam-theme
    networks:
      - internal
      - nginx-proxy_default
    depends_on:
      - postgres
    restart: unless-stopped

  postgres:
    image: postgres:13.2
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      # Set same as KC_DB_PASSWORD
      POSTGRES_PASSWORD: PASSWORD
    volumes:
      - ./postgres:/var/lib/postgresql/data
    networks:
      - internal
    restart: unless-stopped

  account-ms:
    image: aamdigital/account-ms:latest
    depends_on:
      - keycloak
    networks:
      - internal
      - nginx-proxy_default
    environment:
      LETSENCRYPT_HOST: example.com
      VIRTUAL_HOST: example.com
      VIRTUAL_PORT: 3000
      CORS: "*"
      SENTRY_DSN:
      KEYCLOAK_URL: https://example.com
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_PASSWORD: admin
    restart: unless-stopped

networks:
  internal:
  nginx-proxy_default:
    external: true
