services:
  keycloak:
    image: ghcr.io/aam-digital/aam-keycloak:23.0.7
    environment:
      # For all available options see https://www.keycloak.org/server/all-config
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: ${ADMIN_PASSWORD:?No admin password set}
      KC_DB_URL_HOST: postgres
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: ${DB_PASSWORD:?No DB password set}
      KC_PROXY: edge
      KC_HOSTNAME: ${KEYCLOAK_URL:?No Keycloak URL set}
    volumes:
      - ./aam-theme:/opt/keycloak/themes/aam-theme
      - ./aam-theme-com:/opt/keycloak/themes/aam-theme-com
      - ./client_config.json:/client_config.json
      - ./realm_config.json:/realm_config.json
    command: start --optimized --spi-theme-login-theme=aam-theme
    networks:
      - internal
      - external_web
    depends_on:
      - postgres
    restart: unless-stopped

  postgres:
    image: postgres:13.2
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: $DB_PASSWORD
    volumes:
      - ./postgres:/var/lib/postgresql/data
    networks:
      - internal
    restart: unless-stopped

networks:
  internal:
  external_web:
    external: true
