version: '3'

services:
  keycloak:
    # Building from local Dockerfile
    build: .
    environment:
      # For all available options see https://www.keycloak.org/server/all-config
      KEYCLOAK_ADMIN: admin
      KC_DB_URL_HOST: postgres
      KC_DB_USERNAME: keycloak
      KC_PROXY: edge
      KEYCLOAK_ADMIN_PASSWORD: ${ADMIN_PASSWORD:?No admin password set}
      KC_DB_PASSWORD: ${DB_PASSWORD:?No DB password set}
      KC_HOSTNAME: ${KEYCLOAK_URL:?No Keycloak URL set}
      LETSENCRYPT_HOST: $KEYCLOAK_URL
      VIRTUAL_HOST: $KEYCLOAK_URL
      VIRTUAL_PORT: 8080
    volumes:
      - ./aam-theme:/opt/keycloak/themes/aam-theme
    command: start --optimized --spi-theme-login-theme=aam-theme
    networks:
      - internal
      - nginx-proxy_default
    depends_on:
      - postgres
    restart: unless-stopped

  postgres:
    image: postgres:13.2
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: $DB_PASSWORD
    volumes:
      - ./postgres:/var/lib/postgresql/data
    networks:
      - internal
    restart: unless-stopped

  account-ms:
    image: aamdigital/account-ms:latest
    depends_on:
      - keycloak
    networks:
      - internal
      - nginx-proxy_default
    environment:
      LETSENCRYPT_HOST: ${ACCOUNTS_URL:?No Accounts backend URL set}
      VIRTUAL_HOST: $ACCOUNTS_URL
      VIRTUAL_PORT: 3000
      CORS: "*"
      SENTRY_DSN:
      KEYCLOAK_URL: https://$KEYCLOAK_URL
      KEYCLOAK_ADMIN: $ADMIN_PASSWORD
      KEYCLOAK_PASSWORD:
    restart: unless-stopped

networks:
  internal:
  nginx-proxy_default:
    external: true
