services:
  admin-ms:
    image: aamdigital/ndb-admin:latest
    volumes:
      - ./credentials.json:/app/dist/assets/credentials.json
    user: 1000:1000
    environment:
      PUID: 1000
      PGID: 1000
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD:?No Keycloak password set}
      KEYCLOAK_URL: ${KEYCLOAK_URL:?No Keycloak URL set}
      DOMAIN: ${DOMAIN:?No domain set}
    restart: unless-stopped
    networks:
      - admin_api

  admin-oauth2-proxy:
    image: quay.io/oauth2-proxy/oauth2-proxy:v7.6.0
    networks:
      - admin_api
      - external_web
    depends_on:
      - admin-ms
    volumes:
      - "./oauth2-proxy.cfg:/oauth2-proxy.cfg"
    command: --config /oauth2-proxy.cfg
    restart: unless-stopped

networks:
  admin_api: {}
  external_web:
    external: true
