services:
  deployer-ms:
    image: aamdigital/deployer-ms:latest
    user: 1000:1000
    environment:
      PUID: 1000
      PGID: 1000
      SENTRY_DSN: $SENTRY_DSN
      HOSTNAME: $HOSTNAME
      PORT: $PORT
      KEYCLOAK_URL: ${KEYCLOAK_URL:?No Keycloak URL set}
    networks:
      - external_web
    volumes:
      - ./arg-pipe:/app/dist/assets/arg-pipe
      - ./log.txt:/app/dist/assets/log.txt
    restart: unless-stopped

networks:
  external_web:
    external: true
