server {
    listen 443 ssl;
    listen [::]:443 ssl;

    server_name cadvisor.aam-digital.net;

    include /config/nginx/ssl.conf;

    location / {
        include /config/nginx/proxy.conf;
        include /config/nginx/resolver.conf;
        set $upstream_app monitoring-cadvisor-1;
        set $upstream_port 8080;
        set $upstream_proto http;
        proxy_pass $upstream_proto://$upstream_app:$upstream_port;
    }
}
